### ISSUE TITLE
Primary contact is not displaying in corporate modal

### ISSUE THREAD

**Issue by vivanov1410** [escabc/members-search-app#5]
The Primary Contact field is not displaying under the Corporate modal.  An example would be Patrick Goosen under Brock White.

**Comment by vivanov1410** [comment]
Both original and new corporate modal designs don't include primary contact name. We only added it to government modal in latest update.

I can add primary contact name to corporate modal, let me update design first.

**Comment by vivanov1410** [comment]
Do you think this is ok for primary contact placement:
<img width="662" alt="screenshot 2017-05-16 21 25 55" src="https://cloud.githubusercontent.com/assets/1734413/26138552/e05f5c62-3a7e-11e7-93eb-a4e3a374297e.png">

**Comment by TRH-ESCABC** [comment]
Could we change order to: primary contact, email, visit website.

**Comment by vivanov1410** [comment]
Implemented and deployed, closing.
