### ISSUE TITLE
Disabling member from search is not working

### ISSUE THREAD

**Issue by vivanov1410** [escabc/members-search-app#6]
The custom field that we incorporated into the script to override the display of a record isn’t working.  An example of this would be for the member with the last name Hayward.  I have scheduled the expired account to be deleted as it is a duplicate record.  The account will take a few weeks before it is deleted as there is a cool down period to allow for recovery of the member data.  I updated the profile to say don’t show; however, it still shows in the results.

**Comment by vivanov1410** [comment]
Trent, I have checked this user for search exclusion flag but this user doesn't have it in custom fields. There are many users who have flag specified like **Fitzpatrick**.

**Comment by TRH-ESCABC** [comment]
If you search by "Hayward" under the professional member search, the profile with expired status has the custom field set to 'Yes'.  The user created a duplicate member record and changed his first name slightly.  When you view the API data, does the custom field show as having a value under Dave Hayward?

**Comment by TRH-ESCABC** [comment]
I am wondering if something else is happening here. Fitzpatrick, being excluded from the displayed search results. The membership record for Dave Hayward has been scheduled for deletion. I am wondering if that causes his data in the API return to show differently, which is why the exclusion logic isn't working.

**Comment by vivanov1410** [comment]
It might be because custom fields for Hayward looks like this and don't include search exclusion flag:
```
<CustomFieldResponses>
  <CustomFieldResponse FieldCode="ProfessionalEmail" Visibility="">
    <Values>
      <Value>haywardd@ae.ca</Value>
    </Values>
  </CustomFieldResponse>
  <CustomFieldResponse FieldCode="Ethics" Visibility="">
    <Values>
      <Value>YES</Value>
    </Values>
  </CustomFieldResponse>
  <CustomFieldResponse FieldCode="Accreditation" Visibility="">
    <Values>
      <Value>CPESC</Value>
    </Values>
  </CustomFieldResponse>
  <CustomFieldResponse FieldCode="Accred" Visibility="">
    <Values>
      <Value>7249</Value>
    </Values>
  </CustomFieldResponse>
  <CustomFieldResponse FieldCode="RegionInfo" Visibility="">
    <Values>
      <Value>Thompson Okanagan Region</Value>
    </Values>
  </CustomFieldResponse>
</CustomFieldResponses>
```

I am going to close this issue for now since its not a bug on page side, can reopen later.

**Comment by TRH-ESCABC** [comment]
There are two records for Hayward, one under Dave and the other David. The displayed information in the e-mail, which first name was that associated with?

Sent from my iPad

On May 17, 2017, at 8:31 PM, Viatcheslav Ivanov <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #6<https://github.com/escabc/members-search-app/issues/6>.

**Comment by vivanov1410** [comment]
There is a bug with export, its not removing items deleted from yourmembership, going to fix that.

**Comment by TRH-ESCABC** [comment]
The IE bug is fixed.

I had a few others that had observed this issue and it is now working on their machines.

Thanks for addressing that item as it would have likely been a common issue until people updated their systems to the new version of IE.

**Comment by vivanov1410** [comment]
Issue has been fixed and now export functionality will delete members purged from yourmembership. Hayward member is now only one. Closing.
