### ISSUE TITLE
Change color of "Become a Member" button

### ISSUE THREAD

**Issue by vivanov1410** [escabc/members-search-app#7]
The Call to Action button “Become a Member” is currently green.  What’s your thoughts about standardising the button to match other call to action buttons on other pages.  An example is “join now” on the page http://escabc.com/?page=membership_pro

**Comment by vivanov1410** [comment]
I think it's make sense to standardize it. Reason we chose a green color is to match website's color theme. If current accent color is blue then I will have to change search button color so it doesn't blend with call to action button.

**Comment by TRH-ESCABC** [comment]
If you haven't changed the search function button colour. We can leave it the same and just update the "become a member" button if you want. I don't think it is a big issue if they are both blue or is that a web design no-no?

**Comment by vivanov1410** [comment]
@TRH-ESCABC I would better update both buttons so it looks better 😄 
Take a look on design below, what do you think about it:
<img width="838" alt="screenshot 2017-05-16 20 57 49" src="https://cloud.githubusercontent.com/assets/1734413/26137949/910516ce-3a7a-11e7-9a95-66c275b2f8c5.png">

**Comment by TRH-ESCABC** [comment]
I think both the "become a member" and "search" action buttons should be the same shade of blue.

As a user I would realize that both buttons perform a task. I doubt people would be confused.

Sent from my iPad

On May 16, 2017, at 8:59 PM, Viatcheslav Ivanov <notifications@github.com<mailto:notifications@github.com>> wrote:


@TRH-ESCABC<https://github.com/trh-escabc> I would better update both buttons so it looks better 😄
Take a look on design below, what do you think about it:
[screenshot 2017-05-16 20 57 49]<https://cloud.githubusercontent.com/assets/1734413/26137949/910516ce-3a7a-11e7-9a95-66c275b2f8c5.png>

**Comment by vivanov1410** [comment]
Implemented and deployed, closing.
